export enum CancelacionRazonEnum {
  DIRECCION_EQUIVOCADA = 'DIRECCION_EQUIVOCADA',
  PRODUCTOS_INCOMPLETOS = 'PRODUCTOS_INCOMPLETOS',
  PRODUCTO_MAL = 'PRODUCTO_MAL',
  CLIENTE_DESISTIO = 'CLIENTE_DESISTIO',
  OTRO = 'OTRO'
}